/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package websocketclient;

import org.java_websocket.client.WebSocketClient;
import websocketclient.json.User;

/**
 *
 * @author Dominik
 */
public class MainFrame extends javax.swing.JFrame {
    private WebSocketClient client;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(WebSocketClient c) {
        initComponents();
        this.client = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        atrTab = new javax.swing.JTable();
        sendBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(200, 200));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 200));

        atrTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jmeno", null},
                {"Prijmeni", null},
                {"Gender", null},
                {"Verified", null},
                {"Age", null}
            },
            new String [] {
                "Atribut", "Hodnota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        atrTab.setFocusable(false);
        atrTab.setMinimumSize(new java.awt.Dimension(30, 150));
        atrTab.setPreferredSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setViewportView(atrTab);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        sendBtn.setText("SEND");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sendBtn, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        sendBtn.requestFocus();
        User u = new User();
        String name = atrTab.getModel().getValueAt(0, 1).toString();
        String surname = atrTab.getModel().getValueAt(1,1).toString();
        u.setName(name+" "+surname);
        //u.setGender(atrTab.getModel().getValueAt(2,1).toString());
        //u.setVerified(atrTab.getModel().getValueAt(3,1).toString());
        //u.setAge(atrTab.getModel().getValueAt(4,1).toString());
        
        String toSend = name+" "+surname;
        client.send(toSend);
    }//GEN-LAST:event_sendBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable atrTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
